inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.7

Naming/FileName:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
